const $=s=>document.querySelector(s); const app=$('#app');
const SNAME={ds:'数据结构',co:'计算机组成原理',os:'操作系统',cn:'计算机网络'};
let DB, state={subject:'ds',lesson:null,page:1,tab:'slide',query:'',memory:false};
const LSKEY='cs408-allpdf-progress-v1'; const MEMKEY='cs408-allpdf-memory-v1';
let progress=readStore(LSKEY),memory=readStore(MEMKEY);
function readStore(k){try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return {}}} function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function clean(t=''){return t.split('\n').filter(x=>!/^王道考研\/CSKAOYAN\.COM\s*$/.test(x.trim())&&!/^\d{1,3}$/.test(x.trim())).join('\n').replace(/\n{3,}/g,'\n\n').trim()}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function lesson(id){return DB.lessons.find(x=>x.id===id)}
function img(l,p){return `public/${l.slide_base}/${String(p).padStart(3,'0')}.webp`}
function sumimg(l,p){return `public/summaries/${l.id}/${String(p).padStart(3,'0')}.webp`}
function subjectData(sid){return DB.subjects.find(x=>x.id===sid)}
function render(){app.innerHTML=`<div class="app"><header class="top"><button class="brand" id="home"><small>ALL PDF CONTENT = KEY</small><b>408 全量课件复习台</b></button><input class="search" id="search" placeholder="搜索 350 份课件、6058 页文字…" value="${esc(state.query)}"><div class="top-stats"><span>${DB.stats.lessons} 份课件</span><span>${DB.stats.pages} 页</span></div></header><div class="layout"><aside class="sidebar">${sidebar()}</aside><section class="main" id="main">${main()}</section></div></div>`;bind()}
function sidebar(){let s=`<div class="policy"><b>新的整理规则</b><span>PDF 中所有内容均按重点保留；每份课件结尾总结单独列为“必须记”。不再用 S/A/B/C 过滤内容。</span></div><div class="subject-tabs">`;for(const sid of ['ds','co','os','cn'])s+=`<button data-subject="${sid}" class="${state.subject===sid?'active':''}">${SNAME[sid]}</button>`;s+=`</div><div class="side-actions"><button id="memoryMode">总结必记</button><button id="clearSearch">清除搜索</button></div>`;const sub=subjectData(state.subject);for(const ch of sub.chapters){s+=`<details class="chapter" ${state.lesson&&lesson(state.lesson)?.chapter===ch.chapter?'open':''}><summary>${esc(ch.chapter)}<span>${ch.lesson_count}份 · ${ch.page_count}页</span></summary><div class="lessons">`;for(const id of ch.lesson_ids){const l=lesson(id);s+=`<button class="lesson-btn ${state.lesson===id?'active':''}" data-lesson="${id}"><span><b>${esc(l.title)}</b><small>${l.pages}页 · 总结 p.${l.summary_pages.join(',')}</small></span><i class="dot ${progress[id]?'done':''}"></i></button>`}s+=`</div></details>`}return s}
function main(){if(state.query.trim())return searchView();if(state.memory)return memoryView();if(!state.lesson)return homeView();return lessonView(lesson(state.lesson))}
function homeView(){const sub=subjectData(state.subject);let cards='';for(const s of DB.subjects)cards+=`<div class="subject-card" data-home-sub="${s.id}"><h2>${s.name}</h2><p>${s.lesson_count} 份课件 · ${s.page_count} 页 · ${s.chapters.length} 章</p></div>`;const done=Object.keys(progress).filter(k=>progress[k]).length;return `<div class="home-hero"><div class="hero-card"><div class="kicker">以原始课件为准</div><h1>350 份 PDF，全部是重点。</h1><p>不再根据真题频率或 AI 权重删内容。完整课件页、逐页文字、课件结尾总结全部保留。总结页作为必须记忆层，正文作为完整理解层。</p><div class="hero-numbers"><div><b>${DB.stats.lessons}</b><span>原始课件</span></div><div><b>${DB.stats.pages}</b><span>完整页面</span></div><div><b>${DB.stats.explicit_summary_lessons}</b><span>识别到明确回顾页</span></div><div><b>${done}</b><span>已复习课件</span></div></div><div class="progressbar"><i style="width:${done/DB.stats.lessons*100}%"></i></div></div><div class="subject-overview">${cards}</div></div>`}
function lessonView(l){return `<div class="lesson-head"><div class="crumb">${l.subject_name} / ${esc(l.chapter)}</div><div class="lesson-title-row"><div><h1>${esc(l.title)}</h1><p>${l.pages} 页 · 总结页：${l.summary_pages.map(x=>'p.'+x).join('、')} · ${esc(l.summary_method)}</p></div><span class="all-key">全部内容均为重点</span></div><div class="lesson-actions"><button id="markDone" class="${progress[l.id]?'active':''}">${progress[l.id]?'✓ 已完成复习':'标记本课件已复习'}</button><button id="markMemory" class="memory">${memory[l.id]?'✓ 总结已记':'总结标记为已记'}</button><button id="jumpSummary">跳到课件总结</button></div></div><div class="tabs"><button data-tab="slide" class="${state.tab==='slide'?'active':''}">课件页面</button><button data-tab="thumbs" class="${state.tab==='thumbs'?'active':''}">全部页速览</button><button data-tab="text" class="${state.tab==='text'?'active':''}">逐页文字</button><button data-tab="summary" class="${state.tab==='summary'?'active':''}">结尾总结 · 必记</button></div><div class="panel">${tabContent(l)}</div>`}
function tabContent(l){if(state.tab==='summary')return summaryView(l);if(state.tab==='text')return textView(l);if(state.tab==='thumbs')return thumbsView(l);return slideView(l)}
function slideView(l){const p=Math.min(Math.max(1,state.page),l.pages),pt=l.page_texts[p-1];return `<div class="viewer"><div class="slide-area"><div class="viewer-toolbar"><span>${esc(l.title)}</span><label>第 <input id="pageInput" type="number" min="1" max="${l.pages}" value="${p}"> / ${l.pages} 页</label></div><div class="slide-wrap"><a href="${img(l,p)}" target="_blank" title="新窗口打开，可继续放大"><img src="${img(l,p)}" alt="${esc(l.title)} 第${p}页"></a></div><div class="nav-row"><button id="prevPage" ${p<=1?'disabled':''}>← 上一页</button><button id="nextPage" ${p>=l.pages?'disabled':''}>下一页 →</button></div></div><aside class="page-notes"><h3>第 ${p} 页 · 提取文字</h3><div class="page-text">${esc(clean(pt?.text||'（此页主要为图示，请直接看课件页面。）'))}</div><div class="summary-jump">${l.summary_pages.includes(p)?'<b>这是课件结尾总结/回顾页，属于必须记忆内容。</b>':`<button id="goSummaryPage">查看必记总结 p.${l.summary_pages[0]}</button>`}</div></aside></div>`}
function textView(l){return `<div class="text-pages">${l.page_texts.map(p=>`<section class="text-page" id="txt-${p.page}"><h4>第 ${p.page} 页 ${l.summary_pages.includes(p.page)?'· 必记总结页':''}</h4><pre>${esc(clean(p.text)||'（本页主要为图示/结构图，请切换到“课件页面”查看。）')}</pre></section>`).join('')}</div>`}
function thumbsView(l){return `<div class="thumb-grid">${Array.from({length:l.pages},(_,i)=>i+1).map(p=>`<button class="thumb ${l.summary_pages.includes(p)?'summary':''}" data-page="${p}"><img loading="lazy" src="${img(l,p)}"><span>p.${p}${l.summary_pages.includes(p)?' · 必记总结':''}</span></button>`).join('')}</div>`}
function summaryView(l){return `<div class="summary-panel"><div class="summary-banner"><strong>本课件结尾总结：必须记忆</strong><span>这里不再由 AI 自行压缩取舍。优先展示课件原始结尾总结页，并保留原页面图。</span></div><div class="summary-pages">${l.summary_pages.map(p=>`<article class="summary-page"><header>必记总结 · 第 ${p} 页</header><a href="${sumimg(l,p)}" target="_blank"><img loading="lazy" src="${sumimg(l,p)}"></a></article>`).join('')}</div><div class="summary-text"><h3>总结页提取文字</h3><pre>${esc(clean(l.summary_text)||'此总结页主要由图示组成，请以上方原始课件页为准。')}</pre></div></div>`}
function searchView(){const q=state.query.trim().toLowerCase();let results=[];for(const l of DB.lessons){let score=0,hitPage=null,snip='';if((l.title+' '+l.chapter).toLowerCase().includes(q)){score+=20;snip=l.title}for(const p of l.page_texts){const t=(p.text||'').toLowerCase();const at=t.indexOf(q);if(at>=0){score+=2;if(!hitPage){hitPage=p.page;snip=clean(p.text).slice(Math.max(0,at-60),at+180)}}}if(score)results.push({l,score,hitPage,snip})}results.sort((a,b)=>b.score-a.score);return `<div class="search-results"><h2>搜索“${esc(state.query)}” · ${results.length} 份课件命中</h2>${results.slice(0,120).map(r=>`<div class="result" data-result="${r.l.id}" data-hitpage="${r.hitPage||1}"><div class="meta">${r.l.subject_name} / ${esc(r.l.chapter)} · ${r.l.pages}页</div><b>${esc(r.l.title)}</b><p>${esc(r.snip||'标题命中')}</p></div>`).join('')||'<p>没有找到。</p>'}</div>`}
function memoryView(){const ls=DB.lessons.filter(x=>x.subject===state.subject);return `<div class="memory-mode"><h1>${SNAME[state.subject]} · 课件结尾总结必记清单</h1><p>每一份课件都保留。这里把结尾总结单独汇总，便于背诵和查漏。</p>${ls.map(l=>`<article class="memory-item"><header><div><small>${esc(l.chapter)}</small><b>${esc(l.title)}</b></div><button data-mem="${l.id}">${memory[l.id]?'✓ 已记':'标记已记'}</button></header><pre>${esc(clean(l.summary_text).slice(0,1800)||`总结位于第 ${l.summary_pages.join(',')} 页，请打开原页查看。`)}</pre><button class="lesson-btn" data-memory-open="${l.id}"><span><b>打开完整总结页</b><small>p.${l.summary_pages.join(',')}</small></span></button></article>`).join('')}</div>`}
function bind(){ $('#home').onclick=()=>{state.lesson=null;state.memory=false;state.query='';render()};$('#search').oninput=e=>{state.query=e.target.value;state.memory=false;clearTimeout(window.__st);window.__st=setTimeout(render,180)};document.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>{state.subject=b.dataset.subject;state.lesson=null;state.memory=false;render()});document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{state.lesson=b.dataset.lesson;state.page=1;state.tab='slide';state.memory=false;state.query='';render()});$('#memoryMode').onclick=()=>{state.memory=true;state.lesson=null;state.query='';render()};$('#clearSearch').onclick=()=>{state.query='';render()};document.querySelectorAll('[data-home-sub]').forEach(x=>x.onclick=()=>{state.subject=x.dataset.homeSub;render()});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;state.tab='slide';render()});document.querySelectorAll('[data-result]').forEach(x=>x.onclick=()=>{state.lesson=x.dataset.result;state.page=+x.dataset.hitpage;state.query='';state.tab='slide';render()});document.querySelectorAll('[data-memory-open]').forEach(x=>x.onclick=()=>{state.lesson=x.dataset.memoryOpen;state.memory=false;state.tab='summary';render()});document.querySelectorAll('[data-mem]').forEach(x=>x.onclick=()=>{memory[x.dataset.mem]=!memory[x.dataset.mem];save(MEMKEY,memory);render()});if(state.lesson){const l=lesson(state.lesson);$('#markDone').onclick=()=>{progress[l.id]=!progress[l.id];save(LSKEY,progress);render()};$('#markMemory').onclick=()=>{memory[l.id]=!memory[l.id];save(MEMKEY,memory);render()};$('#jumpSummary').onclick=()=>{state.tab='summary';render()};const prev=$('#prevPage'),next=$('#nextPage'),inp=$('#pageInput'),jump=$('#goSummaryPage');if(prev)prev.onclick=()=>{state.page--;render()};if(next)next.onclick=()=>{state.page++;render()};if(inp)inp.onchange=()=>{state.page=Math.min(l.pages,Math.max(1,+inp.value||1));render()};if(jump)jump.onclick=()=>{state.page=l.summary_pages[0];render()}}}
fetch('public/data/all-lessons.json').then(r=>r.json()).then(db=>{DB=db;state.subject='ds';render()}).catch(e=>{app.innerHTML=`<div class="boot">数据加载失败：${esc(String(e))}</div>`})
